name: dotnet fences ci

on:
  push:
    branches-ignore:
      - 'wip/**'
  pull_request:
    branches-ignore:
      - 'wip/**'
  release:
      types: [published]

jobs:
  build:
    strategy:
        matrix:
          os: [macos-latest, windows-latest, ubuntu-latest]
          dotnet: ['8.0.x', '9.0.100-preview.2.24157.14']
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} using dotnet ${{ matrix.dotnet }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version:  |
            8.0.x
            ${{ matrix.dotnet }}
      - name: Build
        run: ./build.cmd